// <auto-generated />
using System;
using LabTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530060154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LabTracker.Models.LabWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("LabWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 9,
                            LabNumber = 1,
                            Notes = "",
                            Status = "Сдана",
                            StudentId = 1,
                            SubjectId = 1,
                            SubmittedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Проектирование БД"
                        },
                        new
                        {
                            Id = 2,
                            Grade = 10,
                            LabNumber = 1,
                            Notes = "",
                            Status = "Сдана",
                            StudentId = 1,
                            SubjectId = 2,
                            SubmittedDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "HTML/CSS основы"
                        },
                        new
                        {
                            Id = 3,
                            LabNumber = 1,
                            Notes = "",
                            Status = "На доработке",
                            StudentId = 2,
                            SubjectId = 1,
                            Title = "Проектирование БД"
                        },
                        new
                        {
                            Id = 4,
                            LabNumber = 1,
                            Notes = "",
                            Status = "Не сдана",
                            StudentId = 3,
                            SubjectId = 3,
                            Title = "Введение в ИСРПО"
                        });
                });

            modelBuilder.Entity("LabTracker.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Арина",
                            Group = "ИСП-232",
                            LastName = "Лойко",
                            MiddleName = "Станиславна"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Пётр",
                            Group = "ИСП-232",
                            LastName = "Иванов",
                            MiddleName = "Сергеевич"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Мария",
                            Group = "ИСП-232",
                            LastName = "Сидорова",
                            MiddleName = "Алексеевна"
                        });
                });

            modelBuilder.Entity("LabTracker.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Базы данных",
                            TeacherName = "Петров А.В."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Веб-разработка",
                            TeacherName = "Смирнова О.И."
                        },
                        new
                        {
                            Id = 3,
                            Name = "ИСРПО",
                            TeacherName = "Козлов Д.Н."
                        });
                });

            modelBuilder.Entity("LabTracker.Models.LabWork", b =>
                {
                    b.HasOne("LabTracker.Models.Student", "Student")
                        .WithMany("LabWorks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabTracker.Models.Subject", "Subject")
                        .WithMany("LabWorks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("LabTracker.Models.Student", b =>
                {
                    b.Navigation("LabWorks");
                });

            modelBuilder.Entity("LabTracker.Models.Subject", b =>
                {
                    b.Navigation("LabWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
